In [1]:
import numpy as np

In [3]:
arr1d = np.array([44,55,66,77])
arr1d

array([44, 55, 66, 77])

In [4]:
arr1d[2]

66

In [5]:
arr1d[3]

77

In [6]:
arr1d[-1]

77

In [9]:
arr1d[1:3]

array([55, 66])

In [7]:
arr1d

array([44, 55, 66, 77])

In [10]:
arr2d= np.array([[22,33,44],[55,66,77],[88,99,100]])
arr2d

array([[ 22,  33,  44],
       [ 55,  66,  77],
       [ 88,  99, 100]])

In [11]:
arr2d[1]

array([55, 66, 77])

In [12]:
arr2d[1][2]

77

In [13]:
# another method
arr2d[1,2]

77

In [18]:
arr2d[:2]

array([[22, 33, 44],
       [55, 66, 77]])

In [14]:
arr2d

array([[ 22,  33,  44],
       [ 55,  66,  77],
       [ 88,  99, 100]])

In [20]:
arr2d[:2,1:]

array([[33, 44],
       [66, 77]])

In [37]:
arr3d=np.array([[[100,200,300],[400,500,600],[700,800,900]],[[1,2,3],[4,5,6],[7,8,9]]])
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [39]:
arr3d.shape

(2, 3, 3)

In [41]:
arr3d.ndim

3

In [42]:
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [47]:
arr3d[1][1]

array([4, 5, 6])

In [49]:
#arr3d[1][1][0]
arr3d[1,1,0]

4

In [54]:
arr3d[0,:2,1:]

array([[200, 300],
       [500, 600]])

In [50]:
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [57]:
arr = np.arange(1,37).reshape(6,6)

In [58]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
#arr[row, column]

In [66]:
arr[:,2]

array([ 3,  9, 15, 21, 27, 33])

In [67]:
arr[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [86]:
arr[2:4,5]

array([18, 24])

In [84]:
arr[0:5:2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

# BooleanIndexing

In [110]:
data = np.random.randn(7,4)
data

array([[-0.71184297, -0.10467161,  1.51712667,  0.10701057],
       [ 0.3399978 , -0.43644333, -0.20005095,  1.33407079],
       [ 1.70995209,  0.46046269, -1.53561888,  1.95002101],
       [ 0.08677235,  0.55976162, -0.29420715,  0.42440901],
       [ 0.58029507,  0.52189328,  1.49781751, -1.72987869],
       [-1.03319922,  0.72160116, -1.9501314 ,  0.66270765],
       [ 1.21760082,  2.20121337, -0.14169522, -0.83268322]])

In [111]:
bol = np.array([True,False,False,False,False,True,False],dtype = "bool")

data[bol]


array([[-0.71184297, -0.10467161,  1.51712667,  0.10701057],
       [-1.03319922,  0.72160116, -1.9501314 ,  0.66270765]])

In [112]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [119]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [120]:
data[names != "Bob"]

array([[ 0.3399978 , -0.43644333, -0.20005095,  1.33407079],
       [ 1.70995209,  0.46046269, -1.53561888,  1.95002101],
       [ 0.58029507,  0.52189328,  1.49781751, -1.72987869],
       [-1.03319922,  0.72160116, -1.9501314 ,  0.66270765],
       [ 1.21760082,  2.20121337, -0.14169522, -0.83268322]])

In [121]:
cond = names != "Bob"

In [122]:
data[cond]

array([[ 0.3399978 , -0.43644333, -0.20005095,  1.33407079],
       [ 1.70995209,  0.46046269, -1.53561888,  1.95002101],
       [ 0.58029507,  0.52189328,  1.49781751, -1.72987869],
       [-1.03319922,  0.72160116, -1.9501314 ,  0.66270765],
       [ 1.21760082,  2.20121337, -0.14169522, -0.83268322]])

In [123]:
data[~cond]

array([[-0.71184297, -0.10467161,  1.51712667,  0.10701057],
       [ 0.08677235,  0.55976162, -0.29420715,  0.42440901]])

In [124]:
data

array([[-0.71184297, -0.10467161,  1.51712667,  0.10701057],
       [ 0.3399978 , -0.43644333, -0.20005095,  1.33407079],
       [ 1.70995209,  0.46046269, -1.53561888,  1.95002101],
       [ 0.08677235,  0.55976162, -0.29420715,  0.42440901],
       [ 0.58029507,  0.52189328,  1.49781751, -1.72987869],
       [-1.03319922,  0.72160116, -1.9501314 ,  0.66270765],
       [ 1.21760082,  2.20121337, -0.14169522, -0.83268322]])

In [129]:
#cond = names != "Bob"
data = np.arange(28).reshape(7,4)
print(data)
print(cond)
data[cond,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [132]:
#cond = names != "Bob"
data = np.arange(28).reshape(7,4)
print(data)
print(cond)
data[~cond,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 1,  2],
       [13, 14]])

In [133]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [136]:
cond = (names=="Bob") | (names=="Joe")
cond

array([ True,  True, False,  True, False,  True,  True])

In [137]:
data[cond]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

# Fancy Indexing 

In [141]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

In [142]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [151]:
arr[[4,0,1,2],[2,3,0,1]]
#(4,2),(0,3),(1,0),(2,1)

array([4., 0., 1., 2.])

In [154]:
arr = np.arange(32).reshape(8,4)
print(arr)
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

# 1[0, 3, 1, 2],5[0, 3, 1, 2],7[0, 3, 1, 2],2[[0, 3, 1, 2]]
# (1,0)(1,3)(1,1)(1,2)(5,0)()()()()()()()()()()().....

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [155]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [159]:
t = arr.T
t

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [157]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [160]:
arr.sort()

In [161]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [162]:
a  = [22,33,44,55,77,55,44,22,11]
a

[22, 33, 44, 55, 77, 55, 44, 22, 11]

In [163]:
st = set(a)

In [164]:
st

{11, 22, 33, 44, 55, 77}

In [165]:
aset = {11,22,33,44,55,66,7,11,33,44}

In [166]:
aset

{7, 11, 22, 33, 44, 55, 66}

In [167]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [168]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [170]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [171]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [172]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [173]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [175]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [177]:
np.stack([arr1,arr2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [178]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [179]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [181]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [185]:
np.vsplit(arr,3)
#np.hsplit()

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [186]:
np.hsplit(arr,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]