In [0]:
import numpy as np

In [0]:
my_list = list(range(1000000))

type(my_list)

list

In [0]:
my_arr = np.arange(1000000)
type(my_arr)

numpy.ndarray

In [0]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
%time 
for _ in range(10): 
  my_arr2 = my_arr * 2

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 7.15 µs


In [0]:
%time 
for _ in range(10): 
  my_list2 = my_list * 2

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.01 µs


In [0]:
data = np.random.randn(5, 3, 3)
data

array([[[ 0.54022052, -0.75062074,  1.19217723],
        [-0.8968544 ,  0.22174349, -0.71869586],
        [ 1.24008378,  0.45413428,  0.59039859]],

       [[-0.45729232, -1.86505299,  1.34701674],
        [-1.12184737,  0.03303153,  0.04730657],
        [ 0.28801043, -0.45716419,  0.15299803]],

       [[ 1.55430749, -0.78767949,  0.88075961],
        [-0.82498877, -0.55647406,  1.01129258],
        [ 0.77109232,  2.06621228,  0.40024025]],

       [[ 0.91350285,  2.15116048, -1.38348984],
        [-0.16962863, -0.18679487, -0.47377115],
        [ 2.18658167,  0.04533907, -0.91325042]],

       [[ 0.91561408, -0.52894945, -0.32822194],
        [-2.52698778,  1.18531332,  0.09271948],
        [ 1.89683542,  0.70702887, -0.21000554]]])

In [0]:
data.ndim

3

In [0]:
data1 = np.random.randn(2,2)
data1.shape

(2, 2)

In [0]:
data1 * 10

array([[-1.08602517,  7.85627614],
       [-6.73926387,  7.24312594]])

In [0]:
data2 = np.random.randn(2,2)
data2.shape

(2, 2)

In [0]:
data1 - data2

array([[-0.15953875,  2.6852483 ],
       [-0.45512674,  0.60203246]])

In [0]:
data1 + data2

array([[-0.05766629, -1.11399308],
       [-0.89272603,  0.84659273]])

In [0]:
data1 / data2

array([[-2.13212704, -0.41357078],
       [ 3.0801073 ,  5.92338734]])

In [0]:
data1 * data2

array([[-0.0055318 , -1.49239447],
       [ 0.14745486,  0.08856904]])

In [0]:
data.shape

(5, 3, 3)

In [0]:
np.dot(data1,data2) # matrix multiplication, numpy func

array([[ 1.0427839 , -0.14060352],
       [-0.5125567 , -0.26433277]])

In [0]:
data1 @ data2 # matrix multiplication

array([[ 1.0427839 , -0.14060352],
       [-0.5125567 , -0.26433277]])

In [0]:
data1.dot(data2) # matrix multiplication , numpy func

array([[ 1.0427839 , -0.14060352],
       [-0.5125567 , -0.26433277]])

In [0]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
print(data1.shape)
print(data1.dtype)
np.ones_like(data1)

(2, 2)
float64


array([[1., 1.],
       [1., 1.]])

In [0]:
np.ones((2,2),dtype='uint8')

array([[1, 1],
       [1, 1]], dtype=uint8)

In [0]:
np.ones_like(data1)

array([[1., 1.],
       [1., 1.]])

In [0]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [0]:
np.full_like(data1,5)

array([[5., 5.],
       [5., 5.]])

In [0]:
arr1 = np.array([1,2,3], dtype=np.float32)
arr1

array([1., 2., 3.], dtype=float32)

In [0]:
arr1 = np.array([1,2.9,3], dtype='float64')

In [0]:
arr1.dtype

dtype('float64')

In [0]:
arr1.astype(np.int)

array([1, 2, 3])

In [0]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [0]:
numeric_strings.astype(np.float)

array([ 1.25, -9.6 , 42.  ])

In [0]:
a = [1,2,3,4]

In [0]:
type(a[2])

int

In [0]:
a[0:1]

[1]

In [0]:
q=np.array([[[[1]]]])

In [0]:
q.ndim

4

In [0]:
q.shape

(1, 1, 1, 1)

In [0]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
arr1[1,2]

6

In [95]:
arr1[1][2]

6

In [96]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
arr1[0:2,2:]

array([[2, 3],
       [6, 7]])